In [1]:
import pandas as pd
import os

In [3]:

data_dir = "/dtu/p1/johlau/Thesis-Synthex/data/QaTa-COV19/QaTa-COV19-v1/Images/"

image_paths = os.listdir(data_dir)

In [4]:
file_sizes = [(i,os.path.getsize(data_dir+i)) for i in image_paths]

In [6]:
df = pd.DataFrame(file_sizes, columns=["file_name","file_size"])
df

           file_name  file_size
0        covid_1.png      24175
1       covid_10.png     451887
2      covid_100.png      23251
3     covid_1000.png      29066
4     covid_1001.png      21743
...              ...        ...
4598   covid_995.png      32083
4599   covid_996.png     474733
4600   covid_997.png      24774
4601   covid_998.png      16028
4602   covid_999.png      19591

[4603 rows x 2 columns]

In [10]:
df.sort_values(by="file_size", ascending=False).iloc[:20]

           file_name  file_size
160   covid_1141.png    2644196
217   covid_1193.png    2621387
2968  covid_3670.png     966615
2338  covid_3102.png     832646
2362  covid_3124.png     783012
3449  covid_4102.png     721996
4192   covid_628.png     689005
3218  covid_3896.png     679385
4510   covid_914.png     677954
2056   covid_285.png     675620
1677  covid_2508.png     668917
3168  covid_3850.png     660852
4289   covid_715.png     660455
1411  covid_2269.png     646546
3204  covid_3883.png     641427
3689  covid_4319.png     638450
946   covid_1850.png     638408
2793  covid_3512.png     635860
1772  covid_2594.png     634684
1801   covid_262.png     633798